che:
    image: 'eclipse/che:6.19.0'
    command: "start"
    environment:
        - CHE_HOST=${FULL_HOSTNAME}
        - CHE_DOCKER_IP_EXTERNAL=${EXTERNAL_IP}
        - CHE_PORT=80
        - CHE_SINGLE_PORT=true
        - CHE_API_EXTERNAL=http://${FULL_HOSTNAME}/api
        - CHE_API=http://${FULL_HOSTNAME}/api
        - CHE_API_INTERNAL=http://${FULL_HOSTNAME}/api
    networks:
        - extnet
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/che:/data
